### PR TITLE
Add framework to customize MarkdigEngine

### PR DESCRIPTION
**Pull request by qinezh**
Need to support two scenarios:

1. Reuse original parser and customize corresponding renderer.
2. Customize both parser and renderer.

### CODE REVIEW

**Comment by qinezh** [comment]
For scenario 1, there's an issue:

as the renderer [will be cached by the first time](https://github.com/lunet-io/markdig/blob/master/src/Markdig/Renderers/RendererBase.cs#L131), it seems that we can't choose different renderers according to different property in same `MarkdownObject` type dynamically.

For example, we need to make

    ```charp
    public class {
    
    }
    ```
to be rendered by original renderer in markdig, and make

    ```charp-lang
    public class {
    
    }
    ```
to be rendered by customize renderer.

Current workaround is to replace the origin renderer in markdig with the customized one, and merge the logic in original renderer. However, it's not a good solution.

**Comment by qinezh** [comment]
@xoofx do you have any idea about it, any suggestion would be appreciated.

**Comment by xoofx** [comment]
You can replace the CodeBlock renderer with your own CodeBlock renderer that would dispatch to different internal renderer to depending on the CodeBlock data.

**Comment by qinezh** [comment]
@xoofx  Thanks your advice, it's pretty helpful :)

**Pull request closed without merging**
